BearingDistance=20
MaxNodeDistance=100
NodeFactor=3
LineFactor=3,
NonJunctionNodeFactor=1.0

#FRC_Variance.FRC_0=2
#FRC_Variance.FRC_1=2
#FRC_Variance.FRC_2=2
#FRC_Variance.FRC_3=2
#FRC_Variance.FRC_4=2
#FRC_Variance.FRC_5=2
#FRC_Variance.FRC_6=2
#FRC_Variance.FRC_7=2

FRC_Variance=2

MinimumAcceptedRating=1800
MaxNumberRetries=3
ConnectedRouteIncrease=0.10
DNPVariance=118

Bearing_Rating.Excellent=100
Bearing_Rating.Good=50
Bearing_Rating.Average=25
Bearing_Rating.Poor=0

Bearing_Intervals.Excellent=6
Bearing_Intervals.Good=12
Bearing_Intervals.Average=18

FRC_Rating.Excellent=100
FRC_Rating.Good=75
FRC_Rating.Average=50
FRC_Rating.Poor=0

FRC_Intervals.Excellent=0
FRC_Intervals.Good=1
FRC_Intervals.Average=2

FOW_Rating.Excellent=100
FOW_Rating.Good=50
FOW_Rating.Average=50
FOW_Rating.Poor=25

Bearing_Rating.MaxScore=100
Bearing_Rating.MaxBearingDiff=100

Calc_Affected_Lines=false
Lines_Directly_Factor=0.95
CompTime4Cache=0
