MaximumDistanceLRP=15000
CheckTurnRestrictions=false
BearingDistance=20
SlipRoadIntermediateLRP=true
SlipRoadIntermediateLRPLowestHighwayFRC=7
MaximumBearingDifferenceExtraLRP=-1
# Alternate path check parameters
EnableAlternatePathCheck=false
#MaximumAlternatePathLengthAbsolute=5
#MaximumNumberAlternatePaths=1
MaximumAlternatePathFRCVariance=1
#MaximumAlternatePathLengthRatio=1.0001